name: BlockEffects
main: net.betterverse.BlockEffects.Main
version: 1.1
commands:
  lampstone:
    description: Enables/disables lampstone mode
    usage: /<command>
    permissions:
    - Lampstone.build
    - Lampstone.break
  endercrystal:
    description: Places and removes endercrystals
    usage: Try /<command> place or /<command> remove
    permissions:
    - BlockEffects.endercystal.place
    - BlockEffects.endercrystal.remove
  blockeffects:
    description: BlockEffects commands
    usage: /<command>
    aliases: [be]
  stack:
    description: Stacks all allowed items in the sender's inventory.
    usage: /<command>
    permission: blockeffects.stack
  quickpickup:
    description: Enables/disables quickpickup mode.
    permission: blockeffects.quickpickup
    usage: /<command>
  throwbuild:
    description: Enables/disables throwbuild mode.
    permission: blockeffects.throwbuild
    usage: /<command>