name: Lampstone
main: net.betterverse.Lampstone.Lampstone
version: 1.1
commands:
  lampstone:
    description: Enables/disables lampstone mode
    usage: /<command>
    permissions:
    - Lampstone.build
    - Lampstone.break